import type { Effort, Impact } from "./types";

type Template = { title: string; impact: Impact; effort: Effort; why: string; how: string[] };

export const RECOMMENDATIONS: Record<string, Template> = {
  https: {
    title: "Serve your site over HTTPS",
    impact: "high",
    effort: "medium",
    why: "Browsers mark HTTP sites as 'Not secure', and Google uses HTTPS as a ranking signal.",
    how: ["Get a free certificate (Let's Encrypt, or enable SSL at your host/Cloudflare).", "Redirect all http:// traffic to https:// with a 301 redirect."],
  },
  "https-redirect": {
    title: "Redirect HTTP to HTTPS",
    impact: "medium",
    effort: "easy",
    why: "Visitors and search engines hitting the http:// version should be sent to the secure version automatically.",
    how: ["Add a permanent (301) redirect from http:// to https:// in your server, host, or CDN settings."],
  },
  ttfb: {
    title: "Reduce server response time",
    impact: "high",
    effort: "medium",
    why: "A slow first byte delays everything else on the page and hurts Core Web Vitals.",
    how: ["Enable page caching (a caching plugin or full-page cache at your host).", "Use a CDN such as Cloudflare.", "Upgrade slow shared hosting or optimize slow database queries."],
  },
  compression: {
    title: "Enable text compression",
    impact: "medium",
    effort: "easy",
    why: "Gzip or Brotli can shrink HTML, CSS and JS by 60 to 80%, making pages load faster.",
    how: ["Turn on Brotli/Gzip in your server (nginx: gzip on;), host control panel, or CDN."],
  },
  "html-size": {
    title: "Reduce HTML size",
    impact: "low",
    effort: "medium",
    why: "Very large HTML documents take longer to download and parse, especially on mobile.",
    how: ["Remove inline SVGs/base64 images you don't need.", "Paginate or lazy-load long lists.", "Move large inline scripts and styles to cached external files."],
  },
  caching: {
    title: "Set browser caching headers",
    impact: "medium",
    effort: "easy",
    why: "Caching lets returning visitors load your site much faster.",
    how: ["Add Cache-Control headers (e.g. max-age=31536000 for versioned static assets).", "Most CDNs and caching plugins can do this for you."],
  },
  "render-blocking": {
    title: "Reduce render-blocking scripts",
    impact: "medium",
    effort: "medium",
    why: "Scripts in the <head> without async/defer block the page from showing.",
    how: ["Add the defer attribute to scripts that don't need to run immediately.", "Load third-party scripts (chat, analytics) with async."],
  },
  "lazy-images": {
    title: "Lazy-load offscreen images",
    impact: "medium",
    effort: "easy",
    why: "Loading every image upfront wastes bandwidth and slows the first view.",
    how: ['Add loading="lazy" to images below the fold.', "Keep the main hero image eager so it loads quickly."],
  },
  "image-dimensions": {
    title: "Add width and height to images",
    impact: "medium",
    effort: "easy",
    why: "Images without dimensions cause layout shift (CLS) as the page loads.",
    how: ["Set width and height attributes on every <img>, or use CSS aspect-ratio."],
  },
  "modern-images": {
    title: "Use modern image formats",
    impact: "medium",
    effort: "medium",
    why: "WebP and AVIF images are typically 25 to 50% smaller than JPEG/PNG at the same quality.",
    how: ["Convert images to WebP/AVIF (Squoosh, an image CDN, or an optimization plugin).", "Serve them with <picture> fallbacks if needed."],
  },
  "page-weight": {
    title: "Reduce total page weight",
    impact: "high",
    effort: "medium",
    why: "Every kilobyte has to be downloaded before the page feels ready. Heavy pages are slow on mobile data and hurt Core Web Vitals.",
    how: [
      "Compress and resize the largest images (listed in the check details) and serve WebP/AVIF.",
      "Remove unused JavaScript libraries, plugins and third-party widgets.",
      "Split large bundles so each page only loads the code it needs.",
    ],
  },
  "request-count": {
    title: "Cut down the number of requests",
    impact: "medium",
    effort: "medium",
    why: "Each script, stylesheet and image is a separate download; many requests delay rendering, especially on slow connections.",
    how: ["Remove unused plugins, fonts and tracking scripts.", "Bundle small CSS/JS files together.", "Lazy-load images and embeds that are below the fold."],
  },
  "large-resources": {
    title: "Shrink oversized files",
    impact: "medium",
    effort: "easy",
    why: "A few very large files (over 300 KB) often account for most of a page's download time.",
    how: ["Resize images to the size they're displayed at and re-export them compressed.", "Minify and tree-shake large JavaScript files.", "Load heavy embeds (videos, maps) only when clicked."],
  },
  title: {
    title: "Add a descriptive page title",
    impact: "high",
    effort: "easy",
    why: "The title is the clickable headline in Google results and browser tabs.",
    how: ["Add <title>Primary keyword | Brand</title> in the <head>.", "Keep it 30 to 60 characters and unique per page."],
  },
  "title-length": {
    title: "Adjust title length",
    impact: "low",
    effort: "easy",
    why: "Titles that are too short miss keywords; too long get cut off in search results.",
    how: ["Aim for 30 to 60 characters, putting the most important words first."],
  },
  "meta-description": {
    title: "Add a meta description",
    impact: "high",
    effort: "easy",
    why: "Search engines often show it under your link. A good one increases click-through rate.",
    how: ['Add <meta name="description" content="..."> to the <head>.', "Write 70 to 160 characters that summarize the page and invite a click."],
  },
  "meta-description-length": {
    title: "Adjust meta description length",
    impact: "low",
    effort: "easy",
    why: "Descriptions outside 70 to 160 characters are often rewritten or truncated by Google.",
    how: ["Rewrite it to 70 to 160 characters with a clear benefit and call to action."],
  },
  h1: {
    title: "Use exactly one H1 heading",
    impact: "medium",
    effort: "easy",
    why: "The H1 tells visitors and search engines what the page is about.",
    how: ["Make the main page heading an <h1>.", "Use <h2> to <h6> for sub-sections instead of extra H1s."],
  },
  "heading-order": {
    title: "Fix heading hierarchy",
    impact: "low",
    effort: "easy",
    why: "Skipping heading levels makes pages harder to navigate for screen readers and less clear for SEO.",
    how: ["Go in order: H1 → H2 → H3. Don't jump from H1 straight to H4."],
  },
  canonical: {
    title: "Add a canonical URL",
    impact: "medium",
    effort: "easy",
    why: "Prevents duplicate-content issues when the same page is reachable at several URLs.",
    how: ['Add <link rel="canonical" href="https://yourdomain.com/page"> to each page.'],
  },
  robots: {
    title: "Add a robots.txt file",
    impact: "medium",
    effort: "easy",
    why: "robots.txt guides search engine crawlers and points them to your sitemap.",
    how: ["Create /robots.txt with: User-agent: * / Allow: / / Sitemap: https://yourdomain.com/sitemap.xml"],
  },
  sitemap: {
    title: "Add an XML sitemap",
    impact: "medium",
    effort: "easy",
    why: "A sitemap helps search engines discover and index all your pages.",
    how: ["Generate /sitemap.xml (most CMSs and SEO plugins do this automatically).", "Submit it in Google Search Console and reference it in robots.txt."],
  },
  noindex: {
    title: "Remove the noindex tag",
    impact: "high",
    effort: "easy",
    why: "This page tells search engines not to index it, so it won't appear in Google.",
    how: ['Remove <meta name="robots" content="noindex"> unless you intentionally want this page hidden.'],
  },
  "structured-data": {
    title: "Add structured data (Schema.org)",
    impact: "medium",
    effort: "medium",
    why: "Structured data can earn rich results (stars, FAQs, breadcrumbs) in Google.",
    how: ["Add JSON-LD for your Organization/LocalBusiness, and Article/Product/FAQ where relevant.", "Validate with Google's Rich Results Test."],
  },
  "open-graph": {
    title: "Add Open Graph and social tags",
    impact: "medium",
    effort: "easy",
    why: "Controls how your page looks when shared on Facebook, LinkedIn, X and WhatsApp.",
    how: ["Add og:title, og:description, og:image (1200×630) and twitter:card meta tags."],
  },
  "image-alt": {
    title: "Add alt text to images",
    impact: "medium",
    effort: "easy",
    why: "Alt text makes images accessible to screen readers and helps them rank in image search.",
    how: ['Describe each meaningful image in its alt attribute. Use alt="" for purely decorative images.'],
  },
  "broken-links": {
    title: "Fix broken links",
    impact: "medium",
    effort: "easy",
    why: "Broken links frustrate visitors and waste search engine crawl budget.",
    how: ["Update or remove the links listed in the SEO checks.", "Add 301 redirects for pages that moved."],
  },
  favicon: {
    title: "Add a favicon",
    impact: "low",
    effort: "easy",
    why: "Favicons appear in browser tabs, bookmarks and Google mobile results, building brand recognition.",
    how: ['Add <link rel="icon" href="/favicon.ico"> (and an apple-touch-icon for iOS).'],
  },
  lang: {
    title: "Set the page language",
    impact: "medium",
    effort: "easy",
    why: "Screen readers and translation tools need to know the page language.",
    how: ['Add lang="en" (or your language) to the <html> tag.'],
  },
  "form-labels": {
    title: "Label your form fields",
    impact: "medium",
    effort: "easy",
    why: "Inputs without labels are unusable for screen reader users.",
    how: ["Connect each input to a <label for=...>, or add aria-label."],
  },
  "button-names": {
    title: "Give buttons and links accessible names",
    impact: "medium",
    effort: "easy",
    why: "Icon-only buttons and links with no text can't be understood by assistive technology.",
    how: ["Add visible text or an aria-label to every button and link."],
  },
  landmarks: {
    title: "Use semantic page landmarks",
    impact: "low",
    effort: "easy",
    why: "Landmarks (<main>, <nav>, <header>, <footer>) let keyboard and screen-reader users jump around quickly.",
    how: ["Wrap the main content in <main> and navigation in <nav>."],
  },
  hsts: {
    title: "Enable HSTS",
    impact: "medium",
    effort: "easy",
    why: "Strict-Transport-Security forces browsers to always use HTTPS, preventing downgrade attacks.",
    how: ["Add header: Strict-Transport-Security: max-age=31536000; includeSubDomains"],
  },
  csp: {
    title: "Add a Content Security Policy",
    impact: "medium",
    effort: "hard",
    why: "CSP greatly reduces the risk of cross-site scripting (XSS) attacks.",
    how: ["Start with Content-Security-Policy-Report-Only to find what you load, then enforce a policy."],
  },
  "x-content-type-options": {
    title: "Add X-Content-Type-Options",
    impact: "low",
    effort: "easy",
    why: "Stops browsers from guessing file types, which can lead to security issues.",
    how: ["Add header: X-Content-Type-Options: nosniff"],
  },
  "frame-options": {
    title: "Protect against clickjacking",
    impact: "medium",
    effort: "easy",
    why: "Without it, other sites can embed your pages in invisible frames to trick users.",
    how: ["Add header: X-Frame-Options: SAMEORIGIN, or CSP frame-ancestors 'self'."],
  },
  "referrer-policy": {
    title: "Set a Referrer-Policy",
    impact: "low",
    effort: "easy",
    why: "Controls how much URL information is shared with other sites.",
    how: ["Add header: Referrer-Policy: strict-origin-when-cross-origin"],
  },
  "server-disclosure": {
    title: "Hide server version details",
    impact: "low",
    effort: "easy",
    why: "Revealing exact server/framework versions helps attackers target known vulnerabilities.",
    how: ["Remove or genericize the Server and X-Powered-By headers in your server config."],
  },
  "mixed-content": {
    title: "Fix mixed content",
    impact: "medium",
    effort: "easy",
    why: "Loading http:// resources on an https:// page triggers browser warnings and can be blocked.",
    how: ["Change all resource URLs (images, scripts, styles) to https:// or protocol-relative."],
  },
  doctype: {
    title: "Add an HTML5 doctype",
    impact: "low",
    effort: "easy",
    why: "Without <!DOCTYPE html>, browsers render in quirks mode, causing layout bugs.",
    how: ["Add <!DOCTYPE html> as the very first line of the page."],
  },
  charset: {
    title: "Declare the character encoding",
    impact: "low",
    effort: "easy",
    why: "Prevents garbled text for special characters.",
    how: ['Add <meta charset="utf-8"> near the top of the <head>.'],
  },
  viewport: {
    title: "Add a mobile viewport tag",
    impact: "high",
    effort: "easy",
    why: "Without it, phones show a zoomed-out desktop page. Google indexes the mobile version first.",
    how: ['Add <meta name="viewport" content="width=device-width, initial-scale=1">.'],
  },
  "zoom-disabled": {
    title: "Allow users to zoom",
    impact: "medium",
    effort: "easy",
    why: "Disabling zoom (user-scalable=no) makes the page hard to read for people with low vision.",
    how: ["Remove user-scalable=no and maximum-scale=1 from the viewport tag."],
  },
  "thin-content": {
    title: "Add more useful content",
    impact: "medium",
    effort: "medium",
    why: "Pages with very little text struggle to rank and may not answer visitor questions.",
    how: ["Aim for at least 300 words of helpful, original content on key pages.", "Answer the questions your customers actually ask."],
  },
  readability: {
    title: "Make your text easier to read",
    impact: "low",
    effort: "medium",
    why: "Shorter sentences and simpler words keep visitors reading and converting.",
    how: ["Break long sentences up.", "Use headings, bullet points and short paragraphs."],
  },
  cta: {
    title: "Add a clear call to action",
    impact: "medium",
    effort: "easy",
    why: "Visitors need an obvious next step (buy, sign up, contact) or they leave.",
    how: ["Add a prominent button such as 'Get started', 'Book a call' or 'Shop now' above the fold."],
  },
  "contact-info": {
    title: "Show contact information",
    impact: "low",
    effort: "easy",
    why: "Visible contact details build trust with visitors and search engines.",
    how: ["Link to a contact page and show an email, phone or address in the footer."],
  },
  "privacy-policy": {
    title: "Link to a privacy policy",
    impact: "low",
    effort: "easy",
    why: "Required by law in many regions if you collect any data (including analytics cookies).",
    how: ["Publish a privacy policy page and link it in your footer."],
  },
};
