-- Share links: a public report is only readable by its exact share_slug, never by listing the table.
-- Before this, anyone with the publishable key could list every scan marked is_public.

drop policy "scans: read own or public" on public.scans;
create policy "scans: read own" on public.scans for select to authenticated using ((select auth.uid()) = user_id);

drop policy "scan_results: read via scan" on public.scan_results;
create policy "scan_results: read via own scan" on public.scan_results for select to authenticated using (
  exists (select 1 from public.scans s where s.id = scan_id and s.user_id = (select auth.uid())));

revoke select on public.scans from anon;
revoke select on public.scan_results from anon;

-- Unguessable slugs only (generated by the app, 16 base62 characters).
alter table public.scans add constraint scans_share_slug_format check (share_slug is null or share_slug ~ '^[A-Za-z0-9]{16}$');

create or replace function public.get_shared_report(p_slug text)
returns table (url text, device text, created_at timestamptz, report jsonb)
language sql stable security definer set search_path = '' as $$
  select s.url, s.device, s.created_at, r.report
  from public.scans s
  join public.scan_results r on r.scan_id = s.id
  where s.share_slug = p_slug and s.is_public and s.status = 'completed'
  limit 1;
$$;

revoke execute on function public.get_shared_report(text) from public;
grant execute on function public.get_shared_report(text) to anon, authenticated;
